security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        my_provider:
            entity:
                class: App\Entity\Usuarios
                property: nombre

    encoders:
        App\Entity\Usuarios:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/v1/auth/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/v1/auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern: ^/api/v1/auth/register
            stateless: true
            anonymous: true


        api:
            pattern: ^/api/v1
            anonymous: false
            stateless: true
            provider: my_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: ^/
            anonymous: ~
            provider: my_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /



    role_hierarchy:
            ROLE_ADMIN:       [ROLE_GESTOR]
            ROLE_GESTOR:      [ROLE_COMPRADOR]
            ROLE_COMPRADOR:   [ROLE_USER]

    access_control:
        # - { path: ^/api/v1/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/(login | $), roles: [ IS_AUTHENTICATHED_ANONYMOUSLY ] }
        - { path: ^/admgest, roles: [ ROLE_ADMIN ] }
        - { path: ^/evegest, roles: [ ROLE_GESTOR ] }
        - { path: ^/usuarios, roles: [ ROLE_COMPRADOR ] }
        - { path: ^/mensajes, roles: [ ROLE_COMPRADOR ] }
        - { path: ^/tramites, roles: [ ROLE_COMPRADOR ] }


            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
